# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2003-07-29 20:29+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: AnimailMain.py:32
#, python-format
msgid "animail: No mail for %s in %s"
msgstr ""

#: AnimailMain.py:34
#, python-format
msgid "1 message for %s in %s"
msgstr ""

#: AnimailMain.py:36
#, python-format
msgid "%d messages for %s in %s"
msgstr ""

#: AnimailMain.py:142
#, python-format
msgid "Trying to connect (%s)"
msgstr ""

#: AnimailMain.py:144 AnimailMain.py:267
#, python-format
msgid "Authentificating (%s)"
msgstr ""

#: AnimailMain.py:147
#, python-format
msgid "Retrieving stats (%s)"
msgstr ""

#: AnimailMain.py:155
#, python-format
msgid "You have %d new messages (%s)"
msgstr ""

#: AnimailMain.py:158
#, python-format
msgid "Creating messages list (%s)"
msgstr ""

#: AnimailMain.py:160
#, python-format
msgid "No new messages (%s)"
msgstr ""

#: AnimailMain.py:196
msgid "No more messages"
msgstr ""

#: AnimailMain.py:200
msgid "Exiting..."
msgstr ""

#: AnimailMain.py:210
#, python-format
msgid "Connection error (%s): "
msgstr ""

#: AnimailMain.py:213
#, python-format
msgid "Protocol Error (%s): "
msgstr ""

#: AnimailMain.py:223
#, python-format
msgid "Timeout expired (%s): "
msgstr ""

#: AnimailMain.py:226
#, python-format
msgid "Configuration error (%s): "
msgstr ""

#: AnimailMain.py:229
#, python-format
msgid "IMAP error (%s): "
msgstr ""

#: AnimailMain.py:235
msgid "Thread exited"
msgstr ""

#: AnimailMain.py:238
#, python-format
msgid "Unhandled exception (%s)! This is probably a bug, please"
msgstr ""

#: AnimailMain.py:239
msgid "send an email to <juanjux@yahoo.es> with the following message:"
msgstr ""

#: AnimailMain.py:256
#, python-format
msgid "Trying to clean downloaded messages from %s"
msgstr ""

#: AnimailMain.py:262
#, python-format
msgid "Waiting %d seconds before connecting again to the server"
msgstr ""

#: AnimailMain.py:265
#, python-format
msgid "(Re)Connecting to %s"
msgstr ""

#: AnimailMain.py:270
#, python-format
msgid "Starting downloaded messages deletion (%s)"
msgstr ""

#: AnimailMain.py:273
msgid "Something bad happened again! Bye server bye..."
msgstr ""

#: AnimailMain.py:276
msgid "The exception text was:"
msgstr ""

#: AnimailMain.py:314
msgid ""
"Warning: Could not get the system TMP directory for checking the  lockfile, "
"continuing anyway"
msgstr ""

#: AnimailMain.py:321
#, python-format
msgid ""
"Error: Another Animail session seems to be active. If not (check with ps aux|"
"grep animail) delete the file  %s"
msgstr ""

#: AnimailMain.py:330
msgid ""
"Warning: Could not get the system TMP directory for creating the lockfile, "
"continuing anyway"
msgstr ""

#: AnimailMain.py:342
#, python-format
msgid "Warning: Could not create the lockfile: %s"
msgstr ""

#: AnimailMain.py:350
msgid ""
"Warning: Could not get the system TMP directory for deleting the lockfile, "
"continuing anyway"
msgstr ""

#: AnimailMain.py:360
#, python-format
msgid "Error trying to delete the lockfile %s: %s continuing anyway"
msgstr ""

#: configlib.py:105
#, python-format
msgid "Critical Error: Can't deliver mail to unexistent mbox!! (%s)"
msgstr ""

#: configlib.py:108
#, python-format
msgid "Critical Error: Destination mbox (%s) can't be a symlink"
msgstr ""

#: configlib.py:116
#, python-format
msgid "Error trying to open the filter file (%s):"
msgstr ""

#: configlib.py:128
msgid "Error compiling regular expression from the filters file\n"
msgstr ""

#: configlib.py:129 configlib.py:148
#, python-format
msgid "the offending regex was: %s"
msgstr ""

#: configlib.py:136
#, python-format
msgid "Error trying to open the accept file (%s):"
msgstr ""

#: configlib.py:147
msgid "Error compiling regular expression from the accepted file\n"
msgstr ""

#: configlib.py:199
msgid "option --download-order supplied with invalid value."
msgstr ""

#: configlib.py:215
msgid "option --max-to-download suplied with invalid value."
msgstr ""

#: configlib.py:243
#, python-format
msgid "%s:error: %s"
msgstr ""

#: configlib.py:316
#, python-format
msgid "Config file %sanimailrc not found!"
msgstr ""

#: configlib.py:320
#, python-format
msgid ""
"Warning: animailrc file should be on %sanimailrc (current location is in %s)"
msgstr ""

#: configlib.py:323
#, python-format
msgid ""
"Warning: animailrc file should be on %sanimailrc (current location is %s)"
msgstr ""

#: configlib.py:329 update_config.py:31
#, python-format
msgid "Error trying to open the config file %s: %s"
msgstr ""

#: configlib.py:333
msgid ""
"ERROR: For security reasons the animailrc config file must have 600 perms!"
msgstr ""

#: configlib.py:334
msgid "(to change the permissions you can do: chmod 600 animailrc)"
msgstr ""

#: configlib.py:338 update_config.py:34
msgid ""
"WARNING: Config file don't exists or it's empty. Please configure Animail"
msgstr ""

#: configlib.py:343 update_config.py:40
#, python-format
msgid "I can't read the config file (%s)!"
msgstr ""

#: configlib.py:376 update_config.py:58
#, python-format
msgid "Error (line %d), the parameter of '%s' is empty"
msgstr ""

#: configlib.py:386
#, python-format
msgid "Config file error (line %d): <server> inside another <server>"
msgstr ""

#: configlib.py:390
#, python-format
msgid "Config file error (line %d): <global> inside <server>"
msgstr ""

#: configlib.py:394
#, python-format
msgid "Config file error (line %d): </global> inside <server>"
msgstr ""

#: configlib.py:398
#, python-format
msgid "Config file error (line %d): <postfilter> inside <server>"
msgstr ""

#: configlib.py:402
#, python-format
msgid "Config file error (line %d): </postfilter> inside <server>"
msgstr ""

#: configlib.py:503
#, python-format
msgid "Error in config file [server section, line %d] (%s)"
msgstr ""

#: configlib.py:505 configlib.py:829 update_config.py:138
msgid "I don't understand: "
msgstr ""

#: configlib.py:506
msgid "(Maybe a <global> or <postfilter> command in a <server> section?)"
msgstr ""

#: configlib.py:511
#, python-format
msgid "Config file error (line %d): <global> inside another <global>"
msgstr ""

#: configlib.py:515
#, python-format
msgid "Config file error (line %d): <server> inside <global>"
msgstr ""

#: configlib.py:519
#, python-format
msgid "Config file error (line %d): </server> inside <global>"
msgstr ""

#: configlib.py:523
#, python-format
msgid "Config file error (line %d): <postfilter> inside <global>"
msgstr ""

#: configlib.py:527
#, python-format
msgid "Config file error (line %d): </postfilter> inside <global>"
msgstr ""

#: configlib.py:592
#, python-format
msgid "Error in download order config (%s), line %d"
msgstr ""

#: configlib.py:650
#, python-format
msgid "Error in 'NotInAcceptFile' config (%s), line %d"
msgstr ""

#: configlib.py:680
#, python-format
msgid "Couldn't open or create the postfiltered messages log mbox file (%s)!!!"
msgstr ""

#: configlib.py:681
msgid "Please check the permissions of the file and his directory"
msgstr ""

#: configlib.py:687 configlib.py:698
#, python-format
msgid "Error in config file [global section, line %d] (%s)"
msgstr ""

#: configlib.py:688
msgid "The value of SMTPSpamCodes must be a comma separated list of numeric"
msgstr ""

#: configlib.py:689
msgid "three digit codes; either some code includes a non-numeric character"
msgstr ""

#: configlib.py:690
msgid "or some code is not three-digits length (or both)"
msgstr ""

#: configlib.py:699 configlib.py:798
msgid "I don't understand: '"
msgstr ""

#: configlib.py:700
msgid "(Maybe a <server> or <postfilter> command in a <global> section?)"
msgstr ""

#: configlib.py:705
#, python-format
msgid "Config file error (line %d): <postfilter> inside another <postfilter>"
msgstr ""

#: configlib.py:708
#, python-format
msgid "Config file error (line %d): <server> inside <postfilter>"
msgstr ""

#: configlib.py:712
#, python-format
msgid "Config file error (line %d): </server> inside <postfilter>"
msgstr ""

#: configlib.py:715
#, python-format
msgid "Config file error (line %d): <global> inside <postfilter>"
msgstr ""

#: configlib.py:718
#, python-format
msgid "Config file error (line %d): </global> inside <postfilter>"
msgstr ""

#: configlib.py:739 configlib.py:748
#, python-format
msgid "Error in configfile [postfilter section, line %d]:"
msgstr ""

#: configlib.py:740
msgid "the argument for KillerReturnValues must be a NUMBER or "
msgstr ""

#: configlib.py:741
msgid "a comma separated list of NUMBERS"
msgstr ""

#: configlib.py:749
msgid "invalid regular expression as argumento to KillerProgramOutput"
msgstr ""

#: configlib.py:767
#, python-format
msgid "Error in configfile [postfiler section, line %d]:"
msgstr ""

#: configlib.py:771
msgid "No Path given to the post-filter"
msgstr ""

#: configlib.py:777
msgid "No PostFilterName given to this filter"
msgstr ""

#: configlib.py:788
msgid "Both KillerReturnValues and KillerProgramOutput non specified"
msgstr ""

#: configlib.py:789
msgid "You must specify at least one of them"
msgstr ""

#: configlib.py:797
#, python-format
msgid "Error in config file [postfilter section, line %d] (%s)"
msgstr ""

#: configlib.py:799
msgid "(Maybe a <server> or <global> command in a <postfilter> section?)"
msgstr ""

#: configlib.py:818
#, python-format
msgid "Config file error (line %d): </server> outside <server>"
msgstr ""

#: configlib.py:822
#, python-format
msgid "Config file error (line %d): </global> outside <global>"
msgstr ""

#: configlib.py:825
#, python-format
msgid "Config file error (line %d): </postfilter> outside <postfilter>"
msgstr ""

#: configlib.py:828 update_config.py:137
#, python-format
msgid "Error in config file (%s, line %d)"
msgstr ""

#: configlib.py:830
msgid "(Maybe a command outside of a <server> or <global> group?)"
msgstr ""

#: configlib.py:835
msgid ""
"Error in config file, 'reply to messages not in the accept file' enabled"
msgstr ""

#: configlib.py:836
msgid "but no ReplyAddress specified"
msgstr ""

#: general.py:157
msgid "Unknow"
msgstr ""

#: general.py:206
msgid "ISAY: (Piping the message to the program)"
msgstr ""

#: imap.py:87 pop3.py:48
#, python-format
msgid "Looking header %d (%s)"
msgstr ""

#: imap.py:95 pop3.py:56
msgid "Server address not given!!"
msgstr ""

#: imap.py:101
#, python-format
msgid ""
"SSL error while trying to connect to the server (%s), be sure that you have "
"configured the correct port for IMAP4-SSL(usually 993)"
msgstr ""

#: imap.py:123 pop3.py:115
#, python-format
msgid "Getting message list (%s)"
msgstr ""

#: imap.py:141 pop3.py:136
msgid "Message number limit reached"
msgstr ""

#: imap.py:157 pop3.py:182
#, python-format
msgid "From: %s"
msgstr ""

#: imap.py:199 pop3.py:194
msgid "Downloaded: "
msgstr ""

#: imap.py:210
msgid "Deleting marked messages..."
msgstr ""

#: imap.py:217
msgid "Deleting already downloaded messages from IMAP4 server..."
msgstr ""

#: imap.py:220
msgid "...done"
msgstr ""

#: logger.py:122
msgid ""
"\n"
"####### Operation summary #######\n"
"\n"
msgstr ""

#: logger.py:128
msgid ""
"\n"
"--- Server: "
msgstr ""

#: logger.py:132
msgid "* Total messages: "
msgstr ""

#: logger.py:136
msgid "* Total volume on server: "
msgstr ""

#: logger.py:140
msgid "* Filtered messages: "
msgstr ""

#: logger.py:144
msgid "\tTotal filtered volume: "
msgstr ""

#: logger.py:148
msgid "* Downloaded messages: "
msgstr ""

#: logger.py:152
msgid "\tDownloaded Volume: "
msgstr ""

#: logger.py:156
msgid "* Postergated messages: "
msgstr ""

#: logger.py:160
msgid "\tPostergated Volume: "
msgstr ""

#: logger.py:165
msgid ""
"\n"
"* Patterns of filtered messages:\n"
msgstr ""

#: logger.py:173
msgid "* Origin of downloaded messages:\n"
msgstr ""

#: logger.py:181
msgid "* Origin of postergated messages:\n"
msgstr ""

#: logger.py:188
msgid "* Incidents:\n"
msgstr ""

#: mailserver.py:106
#, python-format
msgid ""
"The SMTP rejected the message using a configured SMTPSpamCode (%d): Deleting "
"it from the remote server (SMTP: %s)"
msgstr ""

#: mailserver.py:148
#, python-format
msgid "Failure writing to mbox file '%s' (%s)"
msgstr ""

#: mailserver.py:158
#, python-format
msgid "Failure writing or opening the mbox file '%s' (%s)"
msgstr ""

#: mailserver.py:179
#, python-format
msgid "Maildir '%s' was not found"
msgstr ""

#: mailserver.py:191 mailserver.py:193
msgid "already exist"
msgstr ""

#: mailserver.py:211
msgid "failure writing file "
msgstr ""

#: mailserver.py:216
#, python-format
msgid "failure renaming '%s' to '%s'"
msgstr ""

#: mailserver.py:240
#, python-format
msgid "Message %d size exceed limit (%d), deleting it"
msgstr ""

#: mailserver.py:242
#, python-format
msgid "Message %d deleted, size limit reached"
msgstr ""

#: mailserver.py:264 mailserver.py:464
#, python-format
msgid "Ignoring message %d: DONTDELETETHISMESSAGE type message"
msgstr ""

#: mailserver.py:272
#, python-format
msgid "We've an address confirmation from %s, recovering postergated messages"
msgstr ""

#: mailserver.py:279
#, python-format
msgid "%s Address added to auto-accept file"
msgstr ""

#: mailserver.py:297
#, python-format
msgid "Deleting message %d: Don't match anything in accept file"
msgstr ""

#: mailserver.py:318
#, python-format
msgid "Deleting message %d: Header match %s"
msgstr ""

#: mailserver.py:328
#, python-format
msgid "Message %d (from %s) not in accept file: postergating it"
msgstr ""

#: mailserver.py:344
#, python-format
msgid "Message %d (from %s) not in accept file: ignoring it"
msgstr ""

#: mailserver.py:371
#, python-format
msgid "%d mails recovered from %s"
msgstr ""

#: mailserver.py:374
#, python-format
msgid "Error trying to delete the delayed mbox of the address %s"
msgstr ""

#: mailserver.py:375
msgid "The mailbox won't be deleted, if you want to read those messages"
msgstr ""

#: mailserver.py:376
#, python-format
msgid "open it manually (.animail/animailDelayed/%s)"
msgstr ""

#: mailserver.py:377
msgid "The error was: "
msgstr ""

#: mailserver.py:443
#, python-format
msgid "Downloading message %d (%.2f %s), Left: %d"
msgstr ""

#: mailserver.py:453
msgid "\rDownloaded: "
msgstr ""

#: mailserver.py:487
#, python-format
msgid "Executing postfilter %s on message..."
msgstr ""

#: mailserver.py:491
#, python-format
msgid "%s (Postfiltered by'%s')"
msgstr ""

#: mailserver.py:500
msgid "Deleting message"
msgstr ""

#: mailserver.py:504
msgid ""
"The local SMTP rejected this message so it won't be deleted from the mail "
"server:"
msgstr ""

#: mailserver.py:511
msgid ""
"Socket error sending to the local SMTP, it won't be deleted from the mail "
"server:"
msgstr ""

#: mailserver.py:521
msgid ""
"CRITICAL ERROR. There was an error delivering to MBox, aborting, message "
"won't be deleted from the mail server: "
msgstr ""

#: mailserver.py:525
msgid ""
"CRITICAL ERROR. There was an error delivering to Maildir, aborting, message "
"won't be deleted from the mail server: "
msgstr ""

#: pop3.py:63
#, python-format
msgid ""
"SSL error while trying to connect to the server (%s), be sure that you have "
"configured the correct port for POP3-SSL(usually 995)"
msgstr ""

#: pop3.py:145
msgid "Deleting already downloaded messages from POP3 server..."
msgstr ""

#: pop3.py:147
#, python-format
msgid "Deleting message %s"
msgstr ""

#: postfilter.py:41
#, python-format
msgid ""
"Output of the post-filter '%s' was:\n"
"%s"
msgstr ""

#: postfilter.py:47
#, python-format
msgid "Uh, something bad happened while trying to use the post-filter %s"
msgstr ""

#: postfilter.py:48
msgid "Error was:\n"
msgstr ""

#: postfilter.py:51
msgid "Not using filter"
msgstr ""

#: postfilter.py:56
#, python-format
msgid ""
"Killer return code of filter %s matched for this message, won't be delivered"
msgstr ""

#: postfilter.py:62
#, python-format
msgid ""
"Killer output from filter %s matched for this message, won't be delivered"
msgstr ""

#: postfilter.py:80
#, python-format
msgid "Warning: SavePostFilteredMails activated for this %s PostFilter but no"
msgstr ""

#: postfilter.py:81
msgid "PostFilteredMailsMBox configured: Won't save the email"
msgstr ""

#: postfilter.py:83
#, python-format
msgid "Saving message to %s..."
msgstr ""

#: postfilter.py:100
#, python-format
msgid "Sorry, couldn't save the filtered message to %s: %s"
msgstr ""

#: postfilter.py:108
msgid "Error: In log_filtered_mail value is not 1, 2 or 3"
msgstr ""

#: smtp.py:22
#, python-format
msgid "Reply succesfully send to %s"
msgstr ""

#: smtp.py:42
#, python-format
msgid "Confirmation succesfully send to %s"
msgstr ""

#: smtp.py:59
#, python-format
msgid "Error connecting to the SMTP %s"
msgstr ""

#: smtp.py:71
msgid "Closing SMTP connection"
msgstr ""

#: smtp.py:73
msgid "SMTP Error: Already Closed"
msgstr ""

#: smtp.py:81
msgid "ISAY: (Sending the message to the SMTP)"
msgstr ""
